Composition {
	CurrentTime = 0,
	RenderRange = { 0, 299 },
	GlobalRange = { 0, 299 },
	CurrentID = 11,
	HiQ = true,
	PlaybackUpdateMode = 0,
	StereoMode = false,
	Version = "DaVinci Resolve Studio 21.1.0.0017",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		Gigote = Transform {
			CtrlWZoom = false,
			Inputs = {
				Center = Input {
					Value = { 0.499327764222172, 0.49788902273361 },
					Expression = "Point(0.5 + 0.003335*sin(time*0.181+0.38) + 0.002*sin(time*0.477+4.41), 0.5 + 0.003335*cos(time*0.19+4.06) + 0.002*sin(time*0.405+6.24))",
				},
				Angle = Input {
					Value = -0.450741827983177,
					Expression = "0.5*sin(time*0.128+5.16)",
				},
				Input = Input {
					SourceOp = "MediaIn1",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 0, 0 } },
		},
		MediaIn1 = Loader {
			ExtentSet = true,
			CustomData = { MediaProps = { MEDIA_AUDIO_TRACKS_NUM = 1, MEDIA_ID = "1c9ce764-0679-4dc3-b245-f9faa49fa6bb", MEDIA_MARK_OUT = 299, MEDIA_AUDIO_TRACKS_DESC = { { MEDIA_AUDIO_BIT_DEPTH = 32, MEDIA_AUDIO_TRACK_ID = "Timeline Audio", MEDIA_AUDIO_TRACK_NAME = "Timeline Audio [Template Runes]", MEDIA_AUDIO_START_TIME = 0, MEDIA_AUDIO_FRAME_RATE = 60, MEDIA_AUDIO_SAMPLE_RATE = 48000, MEDIA_AUDIO_NUM_CHANNELS = 2 } }, MEDIA_MARK_IN = 0, MEDIA_NUM_LAYERS = 0, MEDIA_FORMAT_TYPE = "PNG", MEDIA_LAYER_DESC = {
					}, MEDIA_NAME = "StatModsTenacityIcon.png", MEDIA_HEIGHT = 100, MEDIA_WIDTH = 100, MEDIA_START_FRAME = 0, MEDIA_SRC_FRAME_RATE = 60, MEDIA_PATH = "C:\\Users\\Tristan\\Videos\\Records\\League Of Legends\\Runes Artworks\\StatMods\\StatModsTenacityIcon.png", MEDIA_HAS_AUDIO = true, MEDIA_NUM_FRAMES = 300, MEDIA_PAR = 1, MEDIA_IS_SOURCE_RES = true }, },
			Inputs = {
				GlobalOut = Input { Value = 299, },
				AudioTrack = Input { Value = FuID { "Timeline Audio" }, },
				Layer = Input { Value = "0", },
				ClipTimeEnd = Input { Value = 299, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				DeepOutputMode = Input {
					Value = 0,
					Disabled = true,
				},
				LeftAudio = Input {
					SourceOp = "Left",
					Source = "Data",
				},
				RightAudio = Input {
					SourceOp = "Right",
					Source = "Data",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 55, 49.5 } },
			Version = 1,
			Clips = {
				Clip {
					ID = "Clip1",
					Multiframe = true,
					Filename = "C:\\Users\\Tristan\\Videos\\Records\\League Of Legends\\Runes Artworks\\StatMods\\StatModsTenacityIcon.png",
					Length = 300,
					LengthSetManually = true,
					GlobalEnd = 299,
					TrimOut = 299,
				}
			}
		},
		MediaOut1 = Saver {
			Inputs = {
				Index = Input { Value = "0", },
				Input = Input {
					SourceOp = "Gigote",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 605, 49.5 } },
		},
		Right = AudioDisplay {
			CtrlWZoom = false,
		},
		Left = AudioDisplay {
			CtrlWZoom = false,
		}
	},
	Frames = {
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Scale = 1,
				},
			},
			Views = {
				RightView = {
					Viewer = {
						Layer = ":Default"
					}
				},
			},
			Paths = {
				Map = {
					["ResolveCaches:"] = "C:\\Users\\Tristan\\Videos\\CacheClip\\728ac7f6-5dc4-446b-ae8d-01740d09aed6\\4859f2cc-b4c1-4888-a66a-1e1e950e4dd3\\06a6a08e-c7ee-4873-960a-1840a250c76c\\Fusion",
				},
			},
			FrameFormat = {
				Width = 100,
				Height = 100,
				Rate = 60,
				GuideRatio = 1.77777777777778,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			Unsorted = {
				GlobalEnd = 299
			},
		}
	},
}